# Import libraries and dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
reviews_dataset=pd.read_csv('goodreads_train.csv')

In [3]:
reviews_dataset

user_id   book_id  \
0     8842281e1d1347389f2ab93d60773d4d  18245960   
1     8842281e1d1347389f2ab93d60773d4d     16981   
2     8842281e1d1347389f2ab93d60773d4d  28684704   
3     8842281e1d1347389f2ab93d60773d4d  27161156   
4     8842281e1d1347389f2ab93d60773d4d  25884323   
...                                ...       ...   
7336  951a6001dea709fe3743516b144634ea   6366110   
7337  951a6001dea709fe3743516b144634ea   1166599   
7338  951a6001dea709fe3743516b144634ea   1268479   
7339  951a6001dea709fe3743516b144634ea    140974   
7340  951a6001dea709fe3743516b144634ea     13891   

                             review_id  rating  \
0     dfdbb7b0eb5a7e4c26d59a937e2e5feb       5   
1     a5d2c3628987712d0e05c4f90798eb67       3   
2     2ede853b14dc4583f96cf5d120af636f       3   
3     ced5675e55cd9d38a524743f5c40996e       0   
4     332732725863131279a8e345b63ac33e       4   
...                                ...     ...   
7336  8c5ce230b614fa7618b52a248eba06c5       5   
7337  7699ac6b00166fb089ae4db2a9e6037d       5   
7338  3ba5204bda91ec80619959fe4b08d00e       5   
7339  e9c43b26b1c0aa2cc02da2e75e3168d0       3   
7340  cea9678a05641fcc81670f8ff2c4f072       5   

                                            review_text  \
0     This is a special book. It started slow for ab...   
1     Recommended by Don Katz. Avail for free in Dec...   
2     A fun, fast paced science fiction thriller. I ...   
3     Recommended reading to understand what is goin...   
4     I really enjoyed this book, and there is a lot...   
...                                                 ...   
7336  This is the third book in Sanderson's Alcatraz...   
7337            Egwene al'Vere is awesome. That is all.   
7338  Just to say two things about Warbreaker: \n 1....   
7339  ** spoiler alert ** \n My main problem with th...   
7340  Winter's Heart is a lovely interlude between t...   

                          date_added                    date_updated  \
0     Sun Jul 30 07:44:10 -0700 2017  Wed Aug 30 00:00:26 -0700 2017   
1     Mon Dec 05 10:46:44 -0800 2016  Wed Mar 22 11:37:04 -0700 2017   
2     Tue Nov 15 11:29:22 -0800 2016  Mon Mar 20 23:40:27 -0700 2017   
3     Wed Nov 09 17:37:04 -0800 2016  Wed Nov 09 17:38:20 -0800 2016   
4     Mon Apr 25 09:31:23 -0700 2016  Mon Apr 25 09:31:23 -0700 2016   
...                              ...                             ...   
7336  Wed Jan 20 18:01:21 -0800 2010  Wed Jan 20 18:03:18 -0800 2010   
7337  Wed Jan 20 17:55:00 -0800 2010  Wed Jan 20 17:57:32 -0800 2010   
7338  Wed Jan 20 17:50:51 -0800 2010  Wed Jan 20 17:53:26 -0800 2010   
7339  Fri Mar 21 09:22:15 -0700 2008  Fri Jul 16 14:17:20 -0700 2010   
7340  Fri Mar 21 09:22:10 -0700 2008  Sat May 28 20:34:50 -0700 2011   

                             read_at                      started_at  n_votes  \
0     Sat Aug 26 12:05:52 -0700 2017  Tue Aug 15 13:23:18 -0700 2017       28   
1                                NaN                             NaN        1   
2     Sat Mar 18 23:22:42 -0700 2017  Fri Mar 17 23:45:40 -0700 2017       22   
3                                NaN                             NaN        5   
4     Sun Jun 26 00:00:00 -0700 2016  Sat May 28 00:00:00 -0700 2016        9   
...                              ...                             ...      ...   
7336  Fri Nov 13 00:00:00 -0800 2009  Fri Nov 13 00:00:00 -0800 2009        0   
7337  Tue Nov 03 00:00:00 -0800 2009  Tue Nov 03 00:00:00 -0800 2009        0   
7338                             NaN                             NaN        0   
7339                             NaN                             NaN        0   
7340                             NaN                             NaN        0   

      n_comments  
0              1  
1              0  
2              0  
3              1  
4              1  
...          ...  
7336           0  
7337           0  
7338           0  
7339           0  
7340           0  

[7341 rows x 11 columns]

In [4]:
reviews_dataset.columns

Index(['user_id', 'book_id', 'review_id', 'rating', 'review_text',
       'date_added', 'date_updated', 'read_at', 'started_at', 'n_votes',
       'n_comments'],
      dtype='object')

# Drop unwanted columns

In [5]:
columns_to_drop=['user_id','review_id','date_added', 'date_updated', 'read_at', 'started_at','n_votes','n_comments']
reviews_dataset=reviews_dataset.drop(columns_to_drop, axis=1)
print(reviews_dataset)

       book_id  rating                                        review_text
0     18245960       5  This is a special book. It started slow for ab...
1        16981       3  Recommended by Don Katz. Avail for free in Dec...
2     28684704       3  A fun, fast paced science fiction thriller. I ...
3     27161156       0  Recommended reading to understand what is goin...
4     25884323       4  I really enjoyed this book, and there is a lot...
...        ...     ...                                                ...
7336   6366110       5  This is the third book in Sanderson's Alcatraz...
7337   1166599       5            Egwene al'Vere is awesome. That is all.
7338   1268479       5  Just to say two things about Warbreaker: \n 1....
7339    140974       3  ** spoiler alert ** \n My main problem with th...
7340     13891       5  Winter's Heart is a lovely interlude between t...

[7341 rows x 3 columns]


In [6]:
print(len(reviews_dataset['review_text']))

7341


## Cleaning the texts

In [7]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus=[]
for i in range(len(reviews_dataset['review_text'])):
    review=re.sub('[^a-zA-Z]',' ',reviews_dataset['review_text'][i])
    review=review.lower()
    review=review.split()
    ps=PorterStemmer()
    all_stopwords=stopwords.words('english')
    all_stopwords.remove('not')
    review=[ps.stem(word) for word in review if word not in set(all_stopwords)]
    review=' '.join(review)
    corpus.append(review)
    

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [8]:
print(corpus[:100])

['special book start slow first third middl third start get interest last third blew mind love good scienc fiction push think thing go hugo winner translat origin chines made interest differ way thing read instanc intermix chines revolutionari histori kept accus peopl reactionari etc book scienc alien scienc describ book impress book ground physic pretti accur far could tell view spoiler though got fold proton dimens think make stuff interest think though would happen seti station receiv messag found someon person monitor answer signal side disillus part book bit dark would like think human reaction discov alien civil hostil would like ender game would band togeth like book unveil trisolaran cultur game smart way build empathi also understand gone across mani centuri know bodi problem unsolv math problem still get made game mayb come next book love quot long histori scientif progress mani proton smash apart acceler physicist mani neutron electron probabl fewer hundr million everi colli

## Making the sentiment column as 1 for positive or 0 for negative using textblob library 

In [9]:
pip install textblob

Note: you may need to restart the kernel to use updated packages.


In [10]:
from textblob import TextBlob

In [11]:
def get_sentiment(text):
    analysis=TextBlob(text)
    polarity=analysis.sentiment.polarity
    return 1 if polarity>0 else 0

In [12]:
reviews_dataset['Sentiment']=reviews_dataset['review_text'].apply(get_sentiment)

In [13]:
reviews_dataset

book_id  rating                                        review_text  \
0     18245960       5  This is a special book. It started slow for ab...   
1        16981       3  Recommended by Don Katz. Avail for free in Dec...   
2     28684704       3  A fun, fast paced science fiction thriller. I ...   
3     27161156       0  Recommended reading to understand what is goin...   
4     25884323       4  I really enjoyed this book, and there is a lot...   
...        ...     ...                                                ...   
7336   6366110       5  This is the third book in Sanderson's Alcatraz...   
7337   1166599       5            Egwene al'Vere is awesome. That is all.   
7338   1268479       5  Just to say two things about Warbreaker: \n 1....   
7339    140974       3  ** spoiler alert ** \n My main problem with th...   
7340     13891       5  Winter's Heart is a lovely interlude between t...   

      Sentiment  
0             1  
1             1  
2             1  
3             1  
4             1  
...         ...  
7336          1  
7337          1  
7338          1  
7339          0  
7340          1  

[7341 rows x 4 columns]

## Creating the Bag of Words model

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 2200)
X = cv.fit_transform(corpus).toarray()
y = reviews_dataset.iloc[:, -1].values

In [15]:
reviews_dataset

book_id  rating                                        review_text  \
0     18245960       5  This is a special book. It started slow for ab...   
1        16981       3  Recommended by Don Katz. Avail for free in Dec...   
2     28684704       3  A fun, fast paced science fiction thriller. I ...   
3     27161156       0  Recommended reading to understand what is goin...   
4     25884323       4  I really enjoyed this book, and there is a lot...   
...        ...     ...                                                ...   
7336   6366110       5  This is the third book in Sanderson's Alcatraz...   
7337   1166599       5            Egwene al'Vere is awesome. That is all.   
7338   1268479       5  Just to say two things about Warbreaker: \n 1....   
7339    140974       3  ** spoiler alert ** \n My main problem with th...   
7340     13891       5  Winter's Heart is a lovely interlude between t...   

      Sentiment  
0             1  
1             1  
2             1  
3             1  
4             1  
...         ...  
7336          1  
7337          1  
7338          1  
7339          0  
7340          1  

[7341 rows x 4 columns]

In [16]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

## Splitting train and test data

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=0)

## Training the Naive Bayes model on the Training set

In [18]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [19]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [1 1]
 [0 0]
 ...
 [1 1]
 [1 1]
 [1 1]]


In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[133  45]
 [497 794]]


0.6310415248468346

## Training the Random forest model on the Training set

In [21]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 300, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=300, random_state=0)

In [22]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 0]
 ...
 [1 1]
 [1 1]
 [1 1]]


In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  72  106]
 [  14 1277]]


0.9183117767188563